![imagen](https://cdn.foodbeast.com/content/wp-content/uploads/2012/03/beer-print-01-selectism.jpg)

# Ejercicio pandas estadística
Para este ejercicio se ha utilizado [un dataset de un concurso de kaggle](https://www.kaggle.com/nickhould/craft-cans), cuyo reto consiste en predecir el tipo de cerveza en función de sus características (nivel de alcohol, amargura, tamaño...).

# Ejercicio 1
Importa las librerias que consideres

In [1]:
import pandas as pd
import numpy as np

## Ejercicio 2
1. Importa el dataset "datasets_beer.csv"
2. Imprime por pantalla los primeros registros.
3. ¿Cuáles son sus columnas?
4. ¿Qué dimensiones tiene el DataFrame?

In [2]:
beers = pd.read_csv("data/datasets_beers.csv")
beers.head()

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces
0,0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0

In [8]:
beers.columns

Index(['Unnamed: 0', 'abv', 'ibu', 'id', 'name', 'style', 'brewery_id',
       'ounces'],
      dtype='object')

In [11]:
beers.shape

(2410, 8)

## Ejercicio 3
[Elimina la columna "Unnamed: 0"](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

In [4]:
beers = beers.drop(columns="Unnamed: 0")
beers

,abv,ibu,id,name,style,brewery_id,ounces
0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0
...,...,...,...,...,...,...,...
2405,0.067,45.0,928,Belgorado,Belgian IPA,424,12.0
2406,0.052,NaN,807,Rail Yard Ale,American Amber / Red Ale,424,12.0
2407,0.055,NaN,620,B3K Black Lager,Schwarzbier,424,12.0
2408,0.055,40.0,145,Silverback Pale Ale,American Pale Ale (APA),424,12.0
2409,0.052,NaN,84,Rail Yard Ale (2009),American Amber / Red Ale,424,12.0

In [48]:
beers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   abv         2348 non-null   float64
 1   ibu         1405 non-null   float64
 2   id          2410 non-null   int64
 3   name        2410 non-null   object
 4   style       2405 non-null   object
 5   brewery_id  2410 non-null   int64
 6   ounces      2410 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 131.9+ KB

In [49]:
beers[beers['ibu'].isna()]

,abv,ibu,id,name,style,brewery_id,ounces
0,0.050,NaN,1436,Pub Beer,American Pale Lager,408,12.0
1,0.066,NaN,2265,Devil's Cup,American Pale Ale (APA),177,12.0
2,0.071,NaN,2264,Rise of the Phoenix,American IPA,177,12.0
3,0.090,NaN,2263,Sinister,American Double / Imperial IPA,177,12.0
4,0.075,NaN,2262,Sex and Candy,American IPA,177,12.0
...,...,...,...,...,...,...,...
2403,0.055,NaN,1045,Wynkoop Pumpkin Ale,Pumpkin Ale,424,12.0
2404,0.075,NaN,1035,Rocky Mountain Oyster Stout,American Stout,424,12.0
2406,0.052,NaN,807,Rail Yard Ale,American Amber / Red Ale,424,12.0
2407,0.055,NaN,620,B3K Black Lager,Schwarzbier,424,12.0
2409,0.052,NaN,84,Rail Yard Ale (2009),American Amber / Red Ale,424,12.0

## Ejercicio 4
¿Cuántas filas y columnas tiene el dataset?

In [26]:
print("Filas: " + str(beers.shape[0]))
print("Columnas: " + str(beers.shape[1]))

Filas: 2410
Columnas: 7

## Ejercicio 5
¿De qué tipo son los datos?

In [28]:
beers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   abv         2348 non-null   float64
 1   ibu         1405 non-null   float64
 2   id          2410 non-null   int64
 3   name        2410 non-null   object
 4   style       2405 non-null   object
 5   brewery_id  2410 non-null   int64
 6   ounces      2410 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 131.9+ KB

## Ejercicio 6
Obtén en un nuevo DataFrame un resumen con las principales estadísticas de las columnas numéricas: mean, max, count, cuartiles...

In [29]:
beers.describe()

               abv          ibu           id   brewery_id       ounces
count  2348.000000  1405.000000  2410.000000  2410.000000  2410.000000
mean      0.059773    42.713167  1431.113278   231.749793    13.592241
std       0.013542    25.954066   752.459975   157.685604     2.352204
min       0.001000     4.000000     1.000000     0.000000     8.400000
25%       0.050000    21.000000   808.250000    93.000000    12.000000
50%       0.056000    35.000000  1453.500000   205.000000    12.000000
75%       0.067000    64.000000  2075.750000   366.000000    16.000000
max       0.128000   138.000000  2692.000000   557.000000    32.000000

## Ejercicio 7
¿Cuántas birras hay de cada estilo en este dataset? [Investiga en la documentación de Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) si puedes hacer un conteo de valores.

In [39]:
beers.describe(include=object)

                   name         style
count              2410          2405
unique             2305            99
top     Nonstop Hef Hop  American IPA
freq                 12           424

In [43]:
beers.style.value_counts()

style
American IPA                      424
American Pale Ale (APA)           245
American Amber / Red Ale          133
American Blonde Ale               108
American Double / Imperial IPA    105
                                 ...
Wheat Ale                           1
Grisette                            1
Flanders Oud Bruin                  1
Braggot                             1
Low Alcohol Beer                    1
Name: count, Length: 99, dtype: int64

## Ejercicio 8
1. Imprime por pantalla los registros desde el décimo hasta el vigésimo
2. De esos registros, imprime por pantalla desde la columna `name` a `ounces`, ambas incluidas
3. Quédate con las columnas `abv`, `ibu` y `ounces`, y además quédate sólo con los registros 10 al 20.
4. Convierte el resultado del apartado 3 en un array de `numpy`

In [3]:
beers.iloc[10:21, :]

,Unnamed: 0,abv,ibu,id,name,style,brewery_id,ounces
10,10,0.072,NaN,2099,Sophomoric Saison,Saison / Farmhouse Ale,177,12.0
11,11,0.073,NaN,2098,Regional Ring Of Fire,Saison / Farmhouse Ale,177,12.0
12,12,0.069,NaN,2097,Garce Selé,Saison / Farmhouse Ale,177,12.0
13,13,0.085,NaN,1980,Troll Destroyer,Belgian IPA,177,12.0
14,14,0.061,60.0,1979,Bitter Bitch,American Pale Ale (APA),177,12.0
15,15,0.060,NaN,2318,Ginja Ninja,Cider,154,12.0
16,16,0.060,NaN,2170,Cherried Away,Cider,154,12.0
17,17,0.060,NaN,2169,Rhubarbarian,Cider,154,12.0
18,18,0.060,NaN,1502,BrightCider,Cider,154,12.0
19,19,0.082,NaN,1593,He Said Baltic-Style Porter,Baltic Porter,368,12.0
20,20,0.082,NaN,1592,He Said Belgian-Style Tripel,Tripel,368,12.0

In [ ]:
beers.iloc[10:21, :].loc[:, "name":"ounces"]

                            name                    style  brewery_id  ounces
10             Sophomoric Saison   Saison / Farmhouse Ale         177    12.0
11         Regional Ring Of Fire   Saison / Farmhouse Ale         177    12.0
12                    Garce Selé   Saison / Farmhouse Ale         177    12.0
13               Troll Destroyer              Belgian IPA         177    12.0
14                  Bitter Bitch  American Pale Ale (APA)         177    12.0
15                   Ginja Ninja                    Cider         154    12.0
16                 Cherried Away                    Cider         154    12.0
17                  Rhubarbarian                    Cider         154    12.0
18                   BrightCider                    Cider         154    12.0
19   He Said Baltic-Style Porter            Baltic Porter         368    12.0
20  He Said Belgian-Style Tripel                   Tripel         368    12.0

In [4]:
beers.iloc[10:21, :].loc[:, ["abv", "ibu", "ounces"]]

      abv   ibu  ounces
10  0.072   NaN    12.0
11  0.073   NaN    12.0
12  0.069   NaN    12.0
13  0.085   NaN    12.0
14  0.061  60.0    12.0
15  0.060   NaN    12.0
16  0.060   NaN    12.0
17  0.060   NaN    12.0
18  0.060   NaN    12.0
19  0.082   NaN    12.0
20  0.082   NaN    12.0

In [7]:
beers_array = np.array(beers.iloc[10:21, :].loc[:, ["abv", "ibu", "ounces"]])
beers_array

array([[ 0.072,    nan, 12.   ],
       [ 0.073,    nan, 12.   ],
       [ 0.069,    nan, 12.   ],
       [ 0.085,    nan, 12.   ],
       [ 0.061, 60.   , 12.   ],
       [ 0.06 ,    nan, 12.   ],
       [ 0.06 ,    nan, 12.   ],
       [ 0.06 ,    nan, 12.   ],
       [ 0.06 ,    nan, 12.   ],
       [ 0.082,    nan, 12.   ],
       [ 0.082,    nan, 12.   ]])

## Ejercicio 9
¿Cuántas onzas pesan todas las birras del dataset?

In [8]:
beers.ounces.sum()

np.float64(32757.3)

## Ejercicio 10
El amargor de las cervezas se mide por su nivel de IBUs.
1. ¿Cuál es el amargor medio de las cervezas?
2. ¿El máximo? ¿Y el mínimo?
3. ¿Qué cerveza es la que tiene el amargor máximo? ¿Cuál es la de amargor mínimo?

In [ ]:
beers[["ibu"]].mean()

ibu    138.0
dtype: float64

In [11]:
print(beers[["ibu"]].max())
print(beers[["ibu"]].min())

ibu    138.0
dtype: float64
ibu    4.0
dtype: float64

In [32]:
beers.ibu.sort_values(ascending=False)

147     138.0
2390    135.0
525     130.0
594     126.0
2145    120.0
        ...
2403      NaN
2404      NaN
2406      NaN
2407      NaN
2409      NaN
Name: ibu, Length: 2410, dtype: float64

In [33]:
beers.loc[beers["ibu"].idxmax(), "name"]

'Bitter Bitch Imperial IPA'

In [36]:
beers.loc[beers["ibu"] == beers["ibu"].max(), "name"]

147    Bitter Bitch Imperial IPA
Name: name, dtype: object

## Ejercicio 11
No queda muy claro cuánto de dispar, de dispersa, es la medida de IBU. Mediante estadística descriptiva (una o dos métricas, sin gráficas), razona la dispersión de la variable IBU.

## Ejercicio 12
¿Existe alguna relación lineal entre las variables numéricas del dataset? Intenta pintar este razonamiento mediante un gráfico

## Ejercicio 13
Representa el nivel de alcohol (columna `abv`) en un histograma. ¿Se trata de una distribución simétrica o asimétrica?

## Ejercicio 14
Representa mediante un *boxplot* de `seaborn` la variable `abv`

## Ejercicio 15
1. ¿Qué estilos son los que tienen en media más alcohol?
2. ¿Y los estilos que son en media más amargos?

## Ejercicio 16
Carga el datasets de cervecerias `datasets_breweries.csv`

## Ejercicio 17
1. Renombra la columna `Unnamed: 0` como `brewery_id`
2. Renombra también la columna `name` por `brewery_name`. ¿Puedes hacer ambos apartados en una sola sentencia?

## Ejercicio 18
Junta los dos datasets que tienes

## Ejercicio 19
1. ¿Cuántos estados diferentes hay?
2. ¿Y ciudades diferentes?
3. ¿Cuántas cervecerías hay?

## Ejercicio 20
Agrupa por estado y ciudad, la media, mediana y máximo nivel de alcohol

## Ejercicio 21
¿Cuáles son las cervezas más amargas que se consumen en Indiana, estado = `IN`?

## Ejercicio 22
Obtén una tabla con los principales estadísticos del campo `ibu`,  a nivel ciudad

## Ejercicio 23
Consigue en un DataFrame de todas las cervezas en cuyas cervecerías al menos haya una cerveza con un `abv` mínimo 0.07.

## Ejercicio 24
Teniendo en cuenta la media de amargor de todas las cervezas, obtén una tabla con las cervezas cuyos estados tengan una media de amargor en cerveza por encima de la media