In [1]:
import pandas as pd
import sqlite3

In [2]:
# Conectamos con la base de datos chinook.db
connection = sqlite3.connect("data/chinook.db")

# Obtenemos un cursor que utilizaremos para hacer las queries
crsr = connection.cursor()

In [3]:
# Con esta función leemos los datos y lo pasamos a un DataFrame de Pandas
def sql_query(query):

    # Ejecuta la query
    crsr.execute(query)

    # Almacena los datos de la query 
    ans = crsr.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in crsr.description]

    return pd.DataFrame(ans,columns=names)

In [4]:
connection

# PRIMERA PARTE

## 1. Obtén los clientes de brasil

In [5]:
sql_query("SELECT FirstName, Country FROM customers WHERE Country = 'Brazil'")

   FirstName Country
0       Luís  Brazil
1    Eduardo  Brazil
2  Alexandre  Brazil
3    Roberto  Brazil
4   Fernanda  Brazil

## 2. Obtén los empleados que son agentes de ventas

In [6]:
sql_query("SELECT FirstName, Title, employeeid FROM employees WHERE Title = 'Sales Support Agent'")

  FirstName                Title  EmployeeId
0      Jane  Sales Support Agent           3
1  Margaret  Sales Support Agent           4
2     Steve  Sales Support Agent           5

## 3. Obtén las canciones de ‘AC/DC’

In [7]:
sql_query("SELECT Name, Composer FROM tracks WHERE Composer = 'AC/DC'")

                           Name Composer
0                       Go Down    AC/DC
1                   Dog Eat Dog    AC/DC
2             Let There Be Rock    AC/DC
3                Bad Boy Boogie    AC/DC
4                 Problem Child    AC/DC
5                      Overdose    AC/DC
6  Hell Ain't A Bad Place To Be    AC/DC
7             Whole Lotta Rosie    AC/DC

## 4. Obtén los campos de los clientes que no sean de USA: Nombre completo, ID, País

In [8]:
sql_query("SELECT FirstName, LastName, CustomerId, Country FROM customers WHERE Country != 'USA'")

    FirstName      LastName  CustomerId         Country
0        Luís     Gonçalves           1          Brazil
1      Leonie        Köhler           2         Germany
2    François      Tremblay           3          Canada
3       Bjørn        Hansen           4          Norway
4   František   Wichterlová           5  Czech Republic
5      Helena          Holý           6  Czech Republic
6      Astrid        Gruber           7         Austria
7        Daan       Peeters           8         Belgium
8        Kara       Nielsen           9         Denmark
9     Eduardo       Martins          10          Brazil
10  Alexandre         Rocha          11          Brazil
11    Roberto       Almeida          12          Brazil
12   Fernanda         Ramos          13          Brazil
13       Mark       Philips          14          Canada
14   Jennifer      Peterson          15          Canada
15     Robert         Brown          29          Canada
16     Edward       Francis          30          Canada
17     Martha          Silk          31          Canada
18      Aaron      Mitchell          32          Canada
19      Ellie      Sullivan          33          Canada
20       João     Fernandes          34        Portugal
21   Madalena       Sampaio          35        Portugal
22     Hannah     Schneider          36         Germany
23       Fynn    Zimmermann          37         Germany
24     Niklas      Schröder          38         Germany
25    Camille       Bernard          39          France
26  Dominique      Lefebvre          40          France
27       Marc        Dubois          41          France
28      Wyatt        Girard          42          France
29   Isabelle       Mercier          43          France
30      Terhi    Hämäläinen          44         Finland
31   Ladislav        Kovács          45         Hungary
32       Hugh      O'Reilly          46         Ireland
33      Lucas       Mancini          47           Italy
34   Johannes  Van der Berg          48     Netherlands
35  Stanisław        Wójcik          49          Poland
36    Enrique         Muñoz          50           Spain
37     Joakim     Johansson          51          Sweden
38       Emma         Jones          52  United Kingdom
39       Phil        Hughes          53  United Kingdom
40      Steve        Murray          54  United Kingdom
41       Mark        Taylor          55       Australia
42      Diego     Gutiérrez          56       Argentina
43       Luis         Rojas          57           Chile
44      Manoj        Pareek          58           India
45       Puja    Srivastava          59           India

## 5. Obtén los empleados que son agentes de ventas: Nombre completo, Dirección (Ciudad, Estado, País) y email

In [9]:
sql_query("SELECT FirstName, LastName, City, State, Country, Email FROM employees WHERE Title = 'Sales Support Agent'")

  FirstName LastName     City State Country                     Email
0      Jane  Peacock  Calgary    AB  Canada      jane@chinookcorp.com
1  Margaret     Park  Calgary    AB  Canada  margaret@chinookcorp.com
2     Steve  Johnson  Calgary    AB  Canada     steve@chinookcorp.com

## 6. Obtén una lista con los países no repetidos a los que se han emitido facturas

In [10]:
sql_query("SELECT DISTINCT BillingCountry FROM invoices")

    BillingCountry
0          Germany
1           Norway
2          Belgium
3           Canada
4              USA
5           France
6          Ireland
7   United Kingdom
8        Australia
9            Chile
10           India
11          Brazil
12        Portugal
13     Netherlands
14           Spain
15          Sweden
16  Czech Republic
17         Finland
18         Denmark
19           Italy
20          Poland
21         Austria
22         Hungary
23       Argentina

## 7. Obtén una lista con los estados de USA no repetidos de donde son los clientes y cuántos clientes en cada uno.

In [11]:
sql_query("SELECT DISTINCT State FROM customers WHERE Country = 'USA'")

   State
0     CA
1     WA
2     NY
3     NV
4     FL
5     MA
6     IL
7     WI
8     TX
9     AZ
10    UT

## 8. Cuántos artículos tiene la factura 37

In [12]:
sql_query("SELECT sum(Quantity) FROM invoice_items WHERE InvoiceId = 37")

   sum(Quantity)
0              4

## 9. Cuántas canciones tiene ‘AC/DC’

In [13]:
sql_query("SELECT count(trackid) FROM tracks WHERE Composer = 'AC/DC'")

   count(trackid)
0               8

## 10. Cuántos artículos tiene cada factura

In [14]:
sql_query("SELECT invoiceid as ID_FACTURA, sum(quantity) as TOT_ART FROM invoice_items GROUP BY invoiceid")

     ID_FACTURA  TOT_ART
0             1        2
1             2        4
2             3        6
3             4        9
4             5       14
..          ...      ...
407         408        4
408         409        6
409         410        9
410         411       14
411         412        1

[412 rows x 2 columns]

## 11. Cuántas facturas hay de cada país

In [15]:
sql_query("SELECT billingCountry as PAIS, count(invoiceid) as TOT_FACT FROM invoices GROUP BY billingCountry")

              PAIS  TOT_FACT
0        Argentina         7
1        Australia         7
2          Austria         7
3          Belgium         7
4           Brazil        35
5           Canada        56
6            Chile         7
7   Czech Republic        14
8          Denmark         7
9          Finland         7
10          France        35
11         Germany        28
12         Hungary         7
13           India        13
14         Ireland         7
15           Italy         7
16     Netherlands         7
17          Norway         7
18          Poland         7
19        Portugal        14
20           Spain         7
21          Sweden         7
22             USA        91
23  United Kingdom        21

## 12. Cuántas facturas ha habido en 2009 y 2011

In [16]:
sql_query("SELECT count(invoiceid) as TOT_FACT FROM invoices WHERE strftime('%Y', invoicedate) = '2009' or strftime('%Y', invoicedate) = '2011'")

   TOT_FACT
0       166

## 13. Cuántas facturas ha habido entre 2009 y 2011

In [17]:
sql_query("SELECT count(invoiceid) as TOT_FACT FROM invoices WHERE strftime('%Y', invoicedate) between '2009' and '2011'")

   TOT_FACT
0       249

## 14. Cuántas clientes hay de España y de Brasil

In [18]:
sql_query("SELECT count(customerid) as TOT_PAIS FROM customers WHERE country = 'Brazil' or country = 'Spain'")

   TOT_PAIS
0         6

## 15. Obtén las canciones que su título empieza por ‘You’

In [19]:
sql_query("SELECT name as NOMBRE_CANCION FROM tracks WHERE name LIKE 'You%'")

                                   NOMBRE_CANCION
0                                 You Oughta Know
1                                       You Learn
2                     You Oughta Know (Alternate)
3                              Your Time Has Come
4                                    You Shook Me
5                                 You Shook Me(2)
6                                 You Fool No One
7             You Fool No One (Alternate Version)
8                              You Keep On Moving
9   You Can't Do it Right (With the One You Love)
10                                   You're Crazy
11                            You Ain't the First
12                              You Could Be Mine
13                You've Got Another Thing Comin'
14                                   You Shook Me
15                        Your Time Is Gonna Come
16                 You've Been A Long Time Coming
17   You're What's Happening (In The World Today)
18                          You Sure Love To Ball
19                                 Your Blue Room
20                                        You Are
21                          You're My Best Friend
22                         You Are The Everything
23                                  You've Got It
24                                    Your Mirror
25                             You Got Me Rocking
26                             You Got Me Rocking
27                             You Better You Bet
28                              You Really Got Me
29                               You Got No Right
30               You're Gonna Break My Hart Again
31                        Your Time Is Gonna Come
32                                    Your Savior
33                                Your Soul Today
34                               You Know My Name
35                           You Know I'm No Good
36  You Know I'm No Good (feat. Ghostface Killah)
37                    You Sent Me Flying / Cherry

# SEGUNDA PARTE

## 1. Facturas de Clientes de Brasil, Nombre del cliente, Id de factura, fecha de la factura y el país de la factura

In [20]:
sql_query('''SELECT firstname, invoiceid, invoicedate, billingcountry
FROM invoices
INNER JOIN customers ON invoices.customerid = customers.customerid
WHERE country = "Brazil"''')

    FirstName  InvoiceId          InvoiceDate BillingCountry
0        Luís         98  2010-03-11 00:00:00         Brazil
1        Luís        121  2010-06-13 00:00:00         Brazil
2        Luís        143  2010-09-15 00:00:00         Brazil
3        Luís        195  2011-05-06 00:00:00         Brazil
4        Luís        316  2012-10-27 00:00:00         Brazil
5        Luís        327  2012-12-07 00:00:00         Brazil
6        Luís        382  2013-08-07 00:00:00         Brazil
7     Eduardo         25  2009-04-09 00:00:00         Brazil
8     Eduardo        154  2010-11-14 00:00:00         Brazil
9     Eduardo        177  2011-02-16 00:00:00         Brazil
10    Eduardo        199  2011-05-21 00:00:00         Brazil
11    Eduardo        251  2012-01-09 00:00:00         Brazil
12    Eduardo        372  2013-07-02 00:00:00         Brazil
13    Eduardo        383  2013-08-12 00:00:00         Brazil
14  Alexandre         57  2009-09-06 00:00:00         Brazil
15  Alexandre         68  2009-10-17 00:00:00         Brazil
16  Alexandre        123  2010-06-17 00:00:00         Brazil
17  Alexandre        252  2012-01-22 00:00:00         Brazil
18  Alexandre        275  2012-04-25 00:00:00         Brazil
19  Alexandre        297  2012-07-28 00:00:00         Brazil
20  Alexandre        349  2013-03-18 00:00:00         Brazil
21    Roberto         34  2009-05-23 00:00:00         Brazil
22    Roberto        155  2010-11-14 00:00:00         Brazil
23    Roberto        166  2010-12-25 00:00:00         Brazil
24    Roberto        221  2011-08-25 00:00:00         Brazil
25    Roberto        350  2013-03-31 00:00:00         Brazil
26    Roberto        373  2013-07-03 00:00:00         Brazil
27    Roberto        395  2013-10-05 00:00:00         Brazil
28   Fernanda         35  2009-06-05 00:00:00         Brazil
29   Fernanda         58  2009-09-07 00:00:00         Brazil
30   Fernanda         80  2009-12-10 00:00:00         Brazil
31   Fernanda        132  2010-07-31 00:00:00         Brazil
32   Fernanda        253  2012-01-22 00:00:00         Brazil
33   Fernanda        264  2012-03-03 00:00:00         Brazil
34   Fernanda        319  2012-11-01 00:00:00         Brazil

## 2. Obtén cada factura asociada a cada agente de ventas con su nombre completo

In [21]:
sql_query('''SELECT i.invoiceid AS FACTURA, e.firstname, e.lastname
          FROM customers as c
          INNER JOIN invoices as i ON c.customerid = i.customerid
          INNER JOIN employees as e ON c.supportrepid = e.employeeid
          ''')

     FACTURA FirstName LastName
0         98      Jane  Peacock
1        121      Jane  Peacock
2        143      Jane  Peacock
3        195      Jane  Peacock
4        316      Jane  Peacock
..       ...       ...      ...
407       88     Steve  Johnson
408      217     Steve  Johnson
409      240     Steve  Johnson
410      262     Steve  Johnson
411      314     Steve  Johnson

[412 rows x 3 columns]

## 3. Obtén el nombre del cliente, el país, el nombre del agente y el total

In [22]:
sql_query('''SELECT customers.firstname as NOMBRE_CLIENTE, customers.country, employees.firstname as NOMBRE_AGENTE
          FROM customers
          INNER JOIN employees on supportrepid = employeeid
          ''')

   NOMBRE_CLIENTE         Country NOMBRE_AGENTE
0            Luís          Brazil          Jane
1          Leonie         Germany         Steve
2        François          Canada          Jane
3           Bjørn          Norway      Margaret
4       František  Czech Republic      Margaret
5          Helena  Czech Republic         Steve
6          Astrid         Austria         Steve
7            Daan         Belgium      Margaret
8            Kara         Denmark      Margaret
9         Eduardo          Brazil      Margaret
10      Alexandre          Brazil         Steve
11        Roberto          Brazil          Jane
12       Fernanda          Brazil      Margaret
13           Mark          Canada         Steve
14       Jennifer          Canada          Jane
15          Frank             USA      Margaret
16           Jack             USA         Steve
17       Michelle             USA          Jane
18            Tim             USA          Jane
19            Dan             USA      Margaret
20          Kathy             USA         Steve
21        Heather             USA      Margaret
22           John             USA      Margaret
23          Frank             USA          Jane
24         Victor             USA         Steve
25        Richard             USA      Margaret
26        Patrick             USA      Margaret
27          Julia             USA         Steve
28         Robert          Canada          Jane
29         Edward          Canada          Jane
30         Martha          Canada         Steve
31          Aaron          Canada      Margaret
32          Ellie          Canada          Jane
33           João        Portugal      Margaret
34       Madalena        Portugal      Margaret
35         Hannah         Germany         Steve
36           Fynn         Germany          Jane
37         Niklas         Germany          Jane
38        Camille          France      Margaret
39      Dominique          France      Margaret
40           Marc          France         Steve
41          Wyatt          France          Jane
42       Isabelle          France          Jane
43          Terhi         Finland          Jane
44       Ladislav         Hungary          Jane
45           Hugh         Ireland          Jane
46          Lucas           Italy         Steve
47       Johannes     Netherlands         Steve
48      Stanisław          Poland      Margaret
49        Enrique           Spain         Steve
50         Joakim          Sweden         Steve
51           Emma  United Kingdom          Jane
52           Phil  United Kingdom          Jane
53          Steve  United Kingdom         Steve
54           Mark       Australia      Margaret
55          Diego       Argentina      Margaret
56           Luis           Chile         Steve
57          Manoj           India          Jane
58           Puja           India          Jane

## 4. Obtén cada artículo de la factura con el nombre de la canción

In [23]:
sql_query('''SELECT init.invoiceid as FACTURA, t.name
          FROM invoice_items as init
          INNER JOIN tracks as t ON init.trackid = t.trackid
          ''')

      FACTURA                                               Name
0           1                                  Balls to the Wall
1           1                                  Restless and Wild
2           2                              Put The Finger On You
3           2                                   Inject The Venom
4           2                                         Evil Walks
...       ...                                                ...
2235      411                                   Looking For Love
2236      411                                    Sweet Lady Luck
2237      411  Feirinha da Pavuna/Luz do Repente/Bagaço da La...
2238      411                                   Samba pras moças
2239      412                                           Hot Girl

[2240 rows x 2 columns]

## 5. Muestra todas las canciones con su nombre, formato, álbum y género

In [39]:
sql_query('''SELECT t.name as NOMBRE_CANCION, m.name as TIPO_ARCHIVO, a.title as ALBUM, g.name as GENERO
          FROM tracks as t
          INNER JOIN media_types as m
          ON t.mediatypeid = m.mediatypeid
          INNER JOIN albums as a
          ON t.albumid = a.albumid
          INNER JOIN genres as g
          ON t.genreid = g.genreid
          ''')

,NOMBRE_CANCION,TIPO_ARCHIVO,ALBUM,GENERO
0,For Those About To Rock (We Salute You),MPEG audio file,For Those About To Rock We Salute You,Rock
1,Balls to the Wall,Protected AAC audio file,Balls to the Wall,Rock
2,Fast As a Shark,Protected AAC audio file,Restless and Wild,Rock
3,Restless and Wild,Protected AAC audio file,Restless and Wild,Rock
4,Princess of the Dawn,Protected AAC audio file,Restless and Wild,Rock
...,...,...,...,...
3498,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,Protected AAC audio file,Respighi:Pines of Rome,Classical
3499,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",Protected AAC audio file,Schubert: The Late String Quartets & String Qu...,Classical
3500,"L'orfeo, Act 3, Sinfonia (Orchestra)",Protected AAC audio file,Monteverdi: L'Orfeo,Classical
3501,"Quintet for Horn, Violin, 2 Violas, and Cello ...",Protected AAC audio file,Mozart: Chamber Music,Classical
3502,"Die Zauberflöte, K.620: ""Der Hölle Rache Kocht...",Protected AAC audio file,Mozart Gala: Famous Arias,Opera

## 6. Cuántas canciones hay en cada playlist

In [25]:
sql_query('''SELECT p.name, count(pt.playlistid)
          from playlist_track as pt
          right JOIN playlists as p
          ON pt.playlistid = p.playlistid
          group by p.playlistid
          ''')

                          Name  count(pt.playlistid)
0                        Music                  3290
1                       Movies                     0
2                     TV Shows                   213
3                   Audiobooks                     0
4                   90’s Music                  1477
5                   Audiobooks                     0
6                       Movies                     0
7                        Music                  3290
8                 Music Videos                     1
9                     TV Shows                   213
10             Brazilian Music                    39
11                   Classical                    75
12   Classical 101 - Deep Cuts                    25
13  Classical 101 - Next Steps                    25
14  Classical 101 - The Basics                    25
15                      Grunge                    15
16         Heavy Metal Classic                    26
17                 On-The-Go 1                     1

## 7. Cuánto ha vendido cada empleado

In [42]:
sql_query('''SELECT e.firstname, sum(i.total) as TOTAL_VENTAS
          from customers as c
          inner join invoices as i
          ON c.customerid = i.customerid
          right join employees as e
          ON c.supportrepid = e.employeeid
          group by e.employeeid
          ''')

  FirstName  TOTAL_VENTAS
0    Andrew           NaN
1     Nancy           NaN
2      Jane        833.04
3  Margaret        775.40
4     Steve        720.16
5   Michael           NaN
6    Robert           NaN
7     Laura           NaN

## 8. ¿Quién ha sido el agente de ventas que más ha vendido en 2009?

## 9. ¿Cuáles son los 3 grupos que más han vendido?